version: '3.8'

services:
  api:
    build: .
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
    env_file:
      - .env
    depends_on:
      - redis
      - mongodb
    restart: unless-stopped
    networks:
      - merch-network

  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"
    volumes:
      - redis-data:/data
    restart: unless-stopped
    networks:
      - merch-network

  mongodb:
    image: mongo:7
    ports:
      - "27017:27017"
    volumes:
      - mongodb-data:/data/db
    environment:
      - MONGO_INITDB_DATABASE=merch-mvp
    restart: unless-stopped
    networks:
      - merch-network

volumes:
  redis-data:
  mongodb-data:

networks:
  merch-network:
    driver: bridge